# Project configuration for mise
[tools]
node = "22"
python = "3.12"

[env]
PROJECT_NAME = "{{ config_root | basename }}"
NODE_ENV = "development"

[tasks.dev]
description = "Start development environment"
run = """
echo "🚀 Development environment ready!"
echo "Node: $(node --version)"
echo "Python: $(python --version)"
"""

[tasks.install]
description = "Install dependencies"
run = """
echo "📦 Installing dependencies..."
if [ -f package.json ]; then npm install; fi
if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
"""
